import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react';

import { layerStyles } from './layer-styles';
import { badgeRecipe, buttonRecipe } from './recipes';
import { textStyles } from './text-styles';

const config = defineConfig({
  globalCss: {
    html: {
      colorPalette: 'brand',
      bg: 'bg.canvas',
      color: 'fg.default',
      colorScheme: 'dark',
      scrollBehavior: 'smooth',
      textSizeAdjust: '100%',
    },
    body: {
      minHeight: '100dvh',
      margin: '0',
      bg: 'bg.canvas',
      color: 'fg.default',
      fontFamily: 'body',
      textRendering: 'optimizeLegibility',
      backgroundColor: 'bg.canvas',
    },
    '::selection': {
      bg: 'accent.secondary',
      color: 'fg.default',
    },
    'a, button': {
      transitionProperty: 'common',
      transitionDuration: 'normal',
      transitionTimingFunction: 'ease-out',
    },
    ':where(button, a, input, textarea, select, summary, [role="button"]):focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 3px var(--chakra-colors-focus-ring)',
    },
  },
  theme: {
    breakpoints: {
      sm: '30rem',
      md: '48rem',
      lg: '64rem',
      xl: '80rem',
      '2xl': '96rem',
    },
    tokens: {
      colors: {
        brand: {
          50: { value: '#e7fbff' },
          100: { value: '#c3f5ff' },
          200: { value: '#9cf0ff' },
          300: { value: '#62ebff' },
          400: { value: '#00e5ff' },
          500: { value: '#00daf3' },
          600: { value: '#00b2c8' },
          700: { value: '#008896' },
          800: { value: '#006875' },
          900: { value: '#004f58' },
        },
        slate: {
          50: { value: '#f8fafc' },
          100: { value: '#e2e8f0' },
          200: { value: '#cbd5e1' },
          300: { value: '#94a3b8' },
          400: { value: '#64748b' },
          500: { value: '#475569' },
          600: { value: '#334155' },
          700: { value: '#1e293b' },
          800: { value: '#0f172a' },
          900: { value: '#020617' },
        },
        success: {
          100: { value: '#052e1b' },
          500: { value: '#22c55e' },
          700: { value: '#86efac' },
        },
        warning: {
          100: { value: '#3b2503' },
          500: { value: '#f59e0b' },
          700: { value: '#fcd34d' },
        },
        danger: {
          100: { value: '#3f1113' },
          500: { value: '#ef4444' },
          700: { value: '#fca5a5' },
        },
      },
      fonts: {
        heading: { value: 'var(--font-heading), system-ui, sans-serif' },
        body: { value: 'var(--font-body), system-ui, sans-serif' },
        label: { value: 'var(--font-label), system-ui, sans-serif' },
      },
      fontSizes: {
        '2xs': { value: '0.6875rem' },
        xs: { value: '0.75rem' },
        sm: { value: '0.875rem' },
        md: { value: '1rem' },
        lg: { value: '1.125rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '2rem' },
        '4xl': { value: '2.5rem' },
        '5xl': { value: '3.375rem' },
        '6xl': { value: '4.375rem' },
      },
      spacing: {
        1: { value: '0.25rem' },
        2: { value: '0.5rem' },
        3: { value: '0.75rem' },
        4: { value: '1rem' },
        6: { value: '1.5rem' },
        8: { value: '2rem' },
        10: { value: '2.5rem' },
        12: { value: '3rem' },
        16: { value: '4rem' },
      },
      radii: {
        sm: { value: '0.125rem' },
        md: { value: '0.25rem' },
        lg: { value: '0.5rem' },
        xl: { value: '0.5rem' },
        '2xl': { value: '0.625rem' },
        '3xl': { value: '0.75rem' },
      },
      shadows: {
        xs: { value: '0 1px 2px rgba(0, 0, 0, 0.24)' },
        sm: { value: '0 1px 2px rgba(0, 0, 0, 0.22), 0 18px 40px -28px rgba(0, 0, 0, 0.52)' },
        md: { value: '0 16px 42px -24px rgba(0, 0, 0, 0.58), 0 28px 80px -40px rgba(0, 0, 0, 0.44)' },
        lg: { value: '0 30px 100px -44px rgba(0, 0, 0, 0.64)' },
        inner: { value: 'inset 0 1px 0 rgba(255,255,255,0.06)' },
      },
      sizes: {
        container: { value: '80rem' },
        content: { value: '56rem' },
        wide: { value: '90rem' },
      },
    },
    semanticTokens: {
      colors: {
        'bg.canvas': { value: '#0a0e14' },
        'bg.subtle': { value: '#10141a' },
        'bg.surface': { value: '#1c2026' },
        'bg.surfaceMuted': { value: '#181c22' },
        'bg.elevated': { value: '#262a31' },
        'bg.inset': { value: '#10141a' },
        'bg.brand': { value: '{colors.brand.800}' },
        'fg.default': { value: '#f0f4f8' },
        'fg.muted': { value: '#bac9cc' },
        'fg.subtle': { value: '#8e9fb1' },
        'fg.brand': { value: '{colors.brand.500}' },
        'fg.onAccent': { value: '#00363d' },
        'border.subtle': { value: 'rgba(59, 73, 76, 0.1)' },
        'border.default': { value: 'rgba(132, 147, 150, 0.2)' },
        'border.strong': { value: 'rgba(0, 229, 255, 0.28)' },
        'accent.primary': { value: '{colors.brand.400}' },
        'accent.primaryHover': { value: '{colors.brand.500}' },
        'accent.primaryActive': { value: '{colors.brand.600}' },
        'accent.secondary': { value: '#10141a' },
        'accent.secondaryHover': { value: '#1c2026' },
        'accent.secondaryActive': { value: '#262a31' },
        'focus.ring': { value: 'rgba(0, 218, 243, 0.28)' },
        'status.success': { value: '{colors.success.500}' },
        'status.successBg': { value: '{colors.success.100}' },
        'status.warning': { value: '{colors.warning.500}' },
        'status.warningBg': { value: '{colors.warning.100}' },
        'status.danger': { value: '{colors.danger.500}' },
        'status.dangerBg': { value: '{colors.danger.100}' },
      },
    },
    textStyles,
    layerStyles,
    recipes: {
      button: buttonRecipe,
      badge: badgeRecipe,
    },
  },
});

export const system = createSystem(defaultConfig, config);
