import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react';

import { layerStyles } from './layer-styles';
import { badgeRecipe, buttonRecipe } from './recipes';
import { textStyles } from './text-styles';

const config = defineConfig({
  globalCss: {
    html: {
      colorPalette: 'brand',
      bg: 'bg.canvas',
      color: 'fg.default',
      scrollBehavior: 'smooth',
      textSizeAdjust: '100%',
    },
    body: {
      minHeight: '100dvh',
      margin: '0',
      bg: 'bg.canvas',
      color: 'fg.default',
      fontFamily: 'body',
      textRendering: 'optimizeLegibility',
      backgroundImage:
        'radial-gradient(circle at top, color-mix(in srgb, var(--chakra-colors-accent-primary) 18%, transparent) 0%, transparent 34%), linear-gradient(180deg, color-mix(in srgb, var(--chakra-colors-bg-canvas) 94%, #10141d) 0%, var(--chakra-colors-bg-canvas) 24rem, color-mix(in srgb, var(--chakra-colors-bg-canvas) 98%, #05070b) 100%)',
      backgroundAttachment: 'fixed',
    },
    '::selection': {
      bg: 'accent.secondary',
      color: 'fg.default',
    },
    'a, button': {
      transitionProperty: 'common',
      transitionDuration: 'normal',
      transitionTimingFunction: 'ease-out',
    },
    ':where(button, a, input, textarea, select, summary, [role="button"]):focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 3px var(--chakra-colors-focus-ring)',
    },
  },
  theme: {
    breakpoints: {
      sm: '30rem',
      md: '48rem',
      lg: '64rem',
      xl: '80rem',
      '2xl': '96rem',
    },
    tokens: {
      colors: {
        brand: {
          50: { value: '#ecfeff' },
          100: { value: '#cffafe' },
          200: { value: '#a5f3fc' },
          300: { value: '#67e8f9' },
          400: { value: '#22d3ee' },
          500: { value: '#06b6d4' },
          600: { value: '#0891b2' },
          700: { value: '#0e7490' },
          800: { value: '#155e75' },
          900: { value: '#164e63' },
        },
        slate: {
          50: { value: '#f8fafc' },
          100: { value: '#e2e8f0' },
          200: { value: '#cbd5e1' },
          300: { value: '#94a3b8' },
          400: { value: '#64748b' },
          500: { value: '#475569' },
          600: { value: '#334155' },
          700: { value: '#1e293b' },
          800: { value: '#0f172a' },
          900: { value: '#020617' },
        },
        success: {
          100: { value: '#052e1b' },
          500: { value: '#22c55e' },
          700: { value: '#86efac' },
        },
        warning: {
          100: { value: '#3b2503' },
          500: { value: '#f59e0b' },
          700: { value: '#fcd34d' },
        },
        danger: {
          100: { value: '#3f1113' },
          500: { value: '#ef4444' },
          700: { value: '#fca5a5' },
        },
      },
      fonts: {
        heading: { value: 'var(--font-heading), system-ui, sans-serif' },
        body: { value: 'var(--font-body), system-ui, sans-serif' },
      },
      fontSizes: {
        '2xs': { value: '0.6875rem' },
        xs: { value: '0.75rem' },
        sm: { value: '0.875rem' },
        md: { value: '1rem' },
        lg: { value: '1.125rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '2rem' },
        '4xl': { value: '2.5rem' },
        '5xl': { value: '3.375rem' },
        '6xl': { value: '4.375rem' },
      },
      spacing: {
        1: { value: '0.25rem' },
        2: { value: '0.5rem' },
        3: { value: '0.75rem' },
        4: { value: '1rem' },
        6: { value: '1.5rem' },
        8: { value: '2rem' },
        10: { value: '2.5rem' },
        12: { value: '3rem' },
        16: { value: '4rem' },
      },
      radii: {
        sm: { value: '0.25rem' },
        md: { value: '0.375rem' },
        lg: { value: '0.5rem' },
        xl: { value: '0.75rem' },
        '2xl': { value: '0.875rem' },
        '3xl': { value: '1.125rem' },
      },
      shadows: {
        xs: { value: '0 1px 2px rgba(0, 0, 0, 0.28)' },
        sm: { value: '0 1px 2px rgba(0, 0, 0, 0.28), 0 18px 40px -28px rgba(0, 0, 0, 0.58)' },
        md: { value: '0 16px 42px -24px rgba(0, 0, 0, 0.62), 0 28px 80px -40px rgba(0, 0, 0, 0.52)' },
        lg: { value: '0 30px 100px -44px rgba(0, 0, 0, 0.72)' },
        inner: { value: 'inset 0 1px 0 rgba(255,255,255,0.06)' },
      },
      sizes: {
        container: { value: '72rem' },
        content: { value: '54rem' },
        wide: { value: '80rem' },
      },
    },
    semanticTokens: {
      colors: {
        'bg.canvas': { value: '#0b0f17' },
        'bg.subtle': { value: '#0f1522' },
        'bg.surface': { value: 'rgba(18, 24, 38, 0.84)' },
        'bg.surfaceMuted': { value: 'rgba(15, 21, 34, 0.92)' },
        'bg.elevated': { value: 'rgba(21, 29, 46, 0.96)' },
        'bg.inset': { value: 'rgba(12, 17, 28, 0.96)' },
        'bg.brand': { value: '{colors.brand.700}' },
        'fg.default': { value: '#f8fafc' },
        'fg.muted': { value: '#a8b3c7' },
        'fg.subtle': { value: '#7f8aa3' },
        'fg.brand': { value: '{colors.brand.300}' },
        'border.subtle': { value: 'rgba(148, 163, 184, 0.14)' },
        'border.default': { value: 'rgba(148, 163, 184, 0.22)' },
        'border.strong': { value: 'rgba(125, 211, 252, 0.34)' },
        'accent.primary': { value: '{colors.brand.400}' },
        'accent.primaryHover': { value: '{colors.brand.300}' },
        'accent.primaryActive': { value: '{colors.brand.500}' },
        'accent.secondary': { value: 'rgba(19, 34, 53, 0.98)' },
        'accent.secondaryHover': { value: 'rgba(24, 43, 67, 0.98)' },
        'accent.secondaryActive': { value: 'rgba(15, 29, 46, 0.98)' },
        'focus.ring': { value: 'rgba(34, 211, 238, 0.28)' },
        'status.success': { value: '{colors.success.500}' },
        'status.successBg': { value: '{colors.success.100}' },
        'status.warning': { value: '{colors.warning.500}' },
        'status.warningBg': { value: '{colors.warning.100}' },
        'status.danger': { value: '{colors.danger.500}' },
        'status.dangerBg': { value: '{colors.danger.100}' },
      },
    },
    textStyles,
    layerStyles,
    recipes: {
      button: buttonRecipe,
      badge: badgeRecipe,
    },
  },
});

export const system = createSystem(defaultConfig, config);
