import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react';

import { layerStyles } from './layer-styles';
import { badgeRecipe, buttonRecipe } from './recipes';
import { textStyles } from './text-styles';

const config = defineConfig({
  globalCss: {
    html: {
      colorPalette: 'brand',
      bg: 'bg.canvas',
      color: 'fg.default',
      scrollBehavior: 'smooth',
      textSizeAdjust: '100%',
    },
    body: {
      minHeight: '100dvh',
      margin: '0',
      bg: 'bg.canvas',
      color: 'fg.default',
      fontFamily: 'body',
      textRendering: 'optimizeLegibility',
      backgroundImage:
        'radial-gradient(circle at top left, color-mix(in srgb, var(--chakra-colors-accent-secondary) 28%, transparent) 0, transparent 22%), radial-gradient(circle at top right, color-mix(in srgb, var(--chakra-colors-brand-100) 34%, transparent) 0, transparent 24%), linear-gradient(180deg, var(--chakra-colors-bg-canvas) 0%, color-mix(in srgb, var(--chakra-colors-bg-canvas) 90%, white) 100%)',
      backgroundAttachment: 'fixed',
    },
    '::selection': {
      bg: 'accent.secondary',
      color: 'fg.default',
    },
    'a, button': {
      transitionProperty: 'common',
      transitionDuration: 'normal',
      transitionTimingFunction: 'ease-out',
    },
    ':where(button, a, input, textarea, select, summary, [role="button"]):focus-visible': {
      outline: 'none',
      boxShadow: '0 0 0 3px var(--chakra-colors-focus-ring)',
    },
  },
  theme: {
    breakpoints: {
      sm: '30rem',
      md: '48rem',
      lg: '64rem',
      xl: '80rem',
      '2xl': '96rem',
    },
    tokens: {
      colors: {
        brand: {
          50: { value: '#eef4ff' },
          100: { value: '#dce7ff' },
          200: { value: '#b9d1ff' },
          300: { value: '#8fb3ff' },
          400: { value: '#5f8fff' },
          500: { value: '#2f63f1' },
          600: { value: '#2146c0' },
          700: { value: '#1c3693' },
          800: { value: '#192d73' },
          900: { value: '#18275d' },
        },
        slate: {
          50: { value: '#f4f6fb' },
          100: { value: '#ebeff6' },
          200: { value: '#d9e0ec' },
          300: { value: '#b7c1d2' },
          400: { value: '#8f9cb0' },
          500: { value: '#677588' },
          600: { value: '#4a5668' },
          700: { value: '#394253' },
          800: { value: '#242c39' },
          900: { value: '#161b24' },
        },
        success: {
          100: { value: '#dbf5e6' },
          500: { value: '#1f8f57' },
          700: { value: '#176642' },
        },
        warning: {
          100: { value: '#fff1d6' },
          500: { value: '#c98016' },
          700: { value: '#8a5c12' },
        },
        danger: {
          100: { value: '#fee5e4' },
          500: { value: '#cc4f45' },
          700: { value: '#8f322c' },
        },
      },
      fonts: {
        heading: { value: 'var(--font-heading), system-ui, sans-serif' },
        body: { value: 'var(--font-body), system-ui, sans-serif' },
      },
      fontSizes: {
        '2xs': { value: '0.6875rem' },
        xs: { value: '0.75rem' },
        sm: { value: '0.875rem' },
        md: { value: '1rem' },
        lg: { value: '1.125rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '2rem' },
        '4xl': { value: '2.5rem' },
        '5xl': { value: '3.375rem' },
        '6xl': { value: '4.375rem' },
      },
      spacing: {
        1: { value: '0.25rem' },
        2: { value: '0.5rem' },
        3: { value: '0.75rem' },
        4: { value: '1rem' },
        6: { value: '1.5rem' },
        8: { value: '2rem' },
        10: { value: '2.5rem' },
        12: { value: '3rem' },
        16: { value: '4rem' },
      },
      radii: {
        sm: { value: '0.5rem' },
        md: { value: '0.75rem' },
        lg: { value: '1rem' },
        xl: { value: '1.25rem' },
        '2xl': { value: '1.5rem' },
        '3xl': { value: '2rem' },
      },
      shadows: {
        xs: { value: '0 1px 2px rgba(21, 29, 41, 0.04)' },
        sm: { value: '0 1px 2px rgba(21, 29, 41, 0.04), 0 16px 36px -30px rgba(21, 29, 41, 0.22)' },
        md: { value: '0 12px 30px -22px rgba(21, 29, 41, 0.2), 0 28px 70px -42px rgba(21, 29, 41, 0.18)' },
        lg: { value: '0 30px 90px -54px rgba(21, 29, 41, 0.28)' },
        inner: { value: 'inset 0 1px 0 rgba(255,255,255,0.42)' },
      },
      sizes: {
        container: { value: '72rem' },
        content: { value: '54rem' },
        wide: { value: '80rem' },
      },
    },
    semanticTokens: {
      colors: {
        'bg.canvas': { value: '#f3f1ec' },
        'bg.subtle': { value: '#ece8df' },
        'bg.surface': { value: 'rgba(255, 255, 252, 0.84)' },
        'bg.surfaceMuted': { value: 'rgba(246, 243, 236, 0.92)' },
        'bg.elevated': { value: 'rgba(255, 255, 253, 0.96)' },
        'bg.inset': { value: 'rgba(232, 226, 214, 0.6)' },
        'bg.brand': { value: '{colors.brand.600}' },
        'fg.default': { value: '#18212f' },
        'fg.muted': { value: '#5b6678' },
        'fg.subtle': { value: '#7a8291' },
        'fg.brand': { value: '{colors.brand.700}' },
        'border.subtle': { value: 'rgba(24, 33, 47, 0.08)' },
        'border.default': { value: 'rgba(24, 33, 47, 0.12)' },
        'border.strong': { value: 'rgba(24, 33, 47, 0.18)' },
        'accent.primary': { value: '{colors.brand.700}' },
        'accent.primaryHover': { value: '{colors.brand.800}' },
        'accent.primaryActive': { value: '{colors.brand.900}' },
        'accent.secondary': { value: '#e8dcc6' },
        'accent.secondaryHover': { value: '#e0d1b4' },
        'accent.secondaryActive': { value: '#d4c29f' },
        'focus.ring': { value: 'rgba(67, 109, 178, 0.24)' },
        'status.success': { value: '{colors.success.600}' },
        'status.successBg': { value: '#ddeee4' },
        'status.warning': { value: '{colors.warning.600}' },
        'status.warningBg': { value: '#f8ebd1' },
        'status.danger': { value: '{colors.danger.600}' },
        'status.dangerBg': { value: '#f8e1dd' },
      },
    },
    textStyles,
    layerStyles,
    recipes: {
      button: buttonRecipe,
      badge: badgeRecipe,
    },
  },
});

export const system = createSystem(defaultConfig, config);
