export {
  createCourse,
  createLessonDraft,
  deleteCourse,
  deleteLesson,
  duplicateCourse,
  createLesson,
  createModule,
  getCourseAccessForUser,
  getCourseBySlug,
  getCourseModules,
  getCourseStructureById,
  listAdminCourses,
  listCoursesForAdmin,
  listPublishedCourses,
  setCourseStatus,
  updateCourse,
  updateLesson,
  updateModule,
} from './service';
export type {
  CourseAccessSummary,
  CourseLessonNode,
  CourseListItem,
  CourseModuleNode,
  CourseStructure,
} from './types';
